### ISSUE TITLE
Themes broken?

### ISSUE THREAD

**Issue by FreshmanPresident** [surrsurus/edgequest#30] opened 2016-03-10 01:33 UTC
[20:29:50] [INFO] EdgeQuest Start 
[20:29:50] [INFO] Theme set: torchlight 
[20:29:50] [SEVERE] AssertionError: Looks like there is invalid or missing data in the `torchlight` theme! Using defaults... 
----- STACK TRACE: -----------------------------
The stack trace has not been appended to your log file.[20:29:58] [INFO] Selecting theme... 
[20:29:58] [INFO] Theme set: magma 
[20:29:58] [SEVERE] AssertionError: Looks like there is invalid or missing data in the `magma` theme! Using defaults... 
----- STACK TRACE: -----------------------------
The stack trace has not been appended to your log file.

**Comment by XavilPergis** [comment] 2016-03-10 01:46
Umm...
I can't help because somebody doesn't know how to log things.

**Comment by surrsurus** [comment] 2016-03-10 02:13
Yes, I can't log things on the code you made, with the logger you also made.
Anyways, I'll work on it. You should really post the stack trace but it's not a big deal right now

**Comment by surrsurus** [comment] 2016-03-10 02:15
I'm not getting this error at all.
1. Can this bug be reproduced
2. or can you describe how to reproduce it?

**Comment by surrsurus** [comment] 2016-03-10 02:29
I can't seem to re-create this bug. When you go to make an issue it specifically asks you to list steps to recreating, so that is a big help if you add that. Thanks for using the log output though. Since I'm not having this issue, I'm going to close this issue for right now. If the problem occurs, just comment in this thread. Thank you.

**Comment by surrsurus** [comment] 2016-03-10 13:53
Max and I aren't having problems. This is not a bug anymore at least.

**Closed by surrsurus** 2016-03-10 13:53 UTC
Labels: bug
